### ISSUE TITLE
Embed Temporal web UI

### ISSUE THREAD

**Issue by jlegrone** [DataDog/temporalite#22]
**Is your feature request related to a problem? Please describe.**

A web UI would simplify local development/debugging and help people new to Temporal explore and get familiar.

**Describe the solution you'd like**

Embed https://github.com/temporalio/ui assets and run https://github.com/temporalio/ui-server as part of the Temporalite server.

**Additional context**

There may be similar efforts planned or ongoing in the https://github.com/temporalio/temporal project, so we should coordinate with maintainers. Preferably this could be exposed as an upstream [temporal.ServerOption](https://pkg.go.dev/go.temporal.io/server@v1.13.1/temporal#ServerOption). If we implement this feature first in Temporalite, then it should be forward-compatible with moving outside of the `temporalite` package at some point.

Note on binary size: while keeping binary size minimal is not an explicit goal of Temporalite, we should be mindful of the binary size change this introduces and consider including a build tag to conditionally skip embedding static assets.

**Comment by schickling** [comment]
As a temporary workaround I've used the following `docker-compose.yml` to connect to Temporalite:

```yaml
version: "3.5"
services:
  temporalite-web:
    container_name: temporalite-web
    environment:
      TEMPORAL_GRPC_ENDPOINT: "localhost:7233"
    image: temporalio/web:1.13.0
    network_mode: host
 ```
